type User = {
    id:string,
    name:string,
    email:string,
    age:number,
};

// * IN this scenario:
//  If we wanted to use TS to create some API for managing users in a web app. In that case we would like to use something that is not exactly the above user type by similar to it.
//  So lets say we want to create a endpoint on this API that allows users to submit info to create a new user. It wont include the id type. This is something that the user will not enter it will be generated by the server.
//  So we then want to define a user type that is similar to the above user type but it does not contain the id property.

type NewUserData = {
    name:string,
    email:string,
    age:number,
};

//? Could we just not solve the problem by making the id field optional. It could technically work but that is not good coding practice.
//? Thus we instead make use of a mapped type:

//! MAPPED TYPES:
// * Mapped types build off of the generic types from earlier. Pass types as arguments using "<>" but what Mapped types allow us to do is get a subset of properties from a new type that we created.

//! Pick Mapped Type
// * Example:
type BetterNewUserData = Pick<User,"name" | "email" | "age" >; //? Pick is only one of several mapped types available to us using TS

let newUserData: BetterNewUserData = {
    name: "Waldo",
    email: "waldoblom@email.com",
    age:22
};

// * Now if we want to add a id
let newUser: User= {
    ...newUserData, //? Spread operator
    id: "student-1"
}

//! Readonly mapped Type
type ConstantUser = Readonly<User>; //? Does not take any extra arguments
let user: ConstantUser = {
    id: '123',
    name: "Waldo",
    email:"waldoblom@email.com",
    age: 22
}

// * We are not able to change the type
//user.id = 231; //! This will cause a compile-time error


//? The type of effect that the Readonly mapped type essentially does:
// type User = {
//     readonly id:string,
//     readonly name:string,
//     readonly email:string,
//     readonly age:number,
// };

//! Partial Mapped Type
type PartialUser = Partial<User>; //? This makes all the fields optional
let partialUser: PartialUser = {
    id:"123",
    //favColor: "blue", //! Not possible as this is not a defined property of the type
}

//TODO: Find out what other mapped types are commonly used
//TODO: Find a exercise to practice this further and to see other real world examples

